#http://localhost:8080/swagger-ui/index.html
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: 1
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase.yml

logging:
  level:
    org:
      springframework:
        security: DEBUG
